### PR TITLE
#401: fix memory leaks, improve design around in-place allocs

### LINKED ISSUE #401: Destructors not firing properly on in-place new allocations causing memory leaks
This is most clearly found by de-serializing a map-like type `std::map<std::string, int>` with a long (non-SSO) string that allocates. This happens to trigger this case as the `std::move` is actually a copy since the underlying type serialized is `std::pair<std::string const, int>`, which is not movable (which is a secondary performance concern).

### PR DESCRIPTION
**Pull request by lifflander**
Fixes #401

### CODE REVIEW

**Comment by lifflander** [comment]
The error checking detects the type difference between the `std::pair<const T, U>` and the new transformed type `std::pair<T, U>` and now fails...

File: src/checkpoint/container/container_serialize.h [hunk 1]
```diff
@@ -73,8 +90,23 @@ serializeContainerCapacity(Serializer& s, ContainerT& cont) {
...
+  // modified, so we have to const_cast this out.
+
+  using ValueT = typename detail::get_value_type<ContainerT>::value_type;
+  for (auto& elm : cont) {
+    if constexpr (std::is_same<ValueT&, decltype(elm)>::value) {
+      s | elm;
+    } else if constexpr (std::is_same<ValueT const&, decltype(elm)>::value) {
+      s | const_cast<ValueT&>(elm);
+    } else {
+      s | reinterpret_cast<ValueT&>(elm);
```
Comment (PhilMiller) [inline src/checkpoint/container/container_serialize.h:118]: Should this case be here? Should it be a `static_assert(dependent_false<ValueT>)`? It's not clear that a `reinterpret_cast` is really the right thing. Maybe comment it if it actually is.

File: src/checkpoint/dispatch/reconstructor.h [hunk 2]
```diff
@@ -49,10 +49,85 @@
...
+/**
+ * \struct InPlaceWrapper
+ *
+ * \brief Wrapper class for a in-place allocation which may not have a paired
+ * destructor. If a user has a pre-existing allocation which magistrate
+ * de-serializes into, it may never be destructed as it is copied or moved
+ * around. This type wraps that allocation and forces it to be destroyed or
+ * explicity requires \c transferOwnership to be called to document that the
+ * user is now responsible for destructing it (normally when the type if put in
+ * a managed pointer, e.g., a std::unique_ptr with a standard deleter.
```
Comment (PhilMiller) [inline src/checkpoint/dispatch/reconstructor.h]: This comment seems to trail off, or something. Parenthetical is unclosed, and the grammar doesn't make sense.

Comment (lifflander) [reply src/checkpoint/dispatch/reconstructor.h]: Good call, I didn't finish writing this one!

File: src/checkpoint/container/container_serialize.h (hunk 1 above)
Comment (lifflander) [reply src/checkpoint/container/container_serialize.h:118]: I've added comments. Do they make sense? Do you see a better way of handling this case with `std::pair<T const, U>` -> `std::pair<T, U>`

Comment (PhilMiller) [reply src/checkpoint/container/container_serialize.h:118]: Yeah, that makes sense now. I was mostly confused about the last case, but it's good to have them all described like this.

Is there a reason to have the `#if / #else`? It doesn't seem like the error checking case adds any overhead

Comment (lifflander) [reply src/checkpoint/container/container_serialize.h:118]: No, I actually added that just for cleanliness to made it clear that it's not a correctness requirement to adjust the types. Just purely for error checking (aligning the types).

**Review by nlslatt — APPROVED** [review]
