### PR TITLE
247 dynrankview fails to serialize when rank is 0

### LINKED ISSUE #247: `DynRankView` fails to serialize when rank is 0

### PR DESCRIPTION
**Pull request by lifflander**
Fixes #247

### CODE REVIEW

**Comment by PhilMiller** [comment]
This looks wrong. A rank 0 view has a single scalar value

**Review by nlslatt — CHANGES_REQUESTED** [review]
From a brief discussion with @rppawlo, it sounds like an uninitialized DynRankView will have dim 0 and size 0, while a single scalar DynRankView will have dim 0 and non-zero size. This PR, including tests, should be updated to reflect that.

**Review by nlslatt — APPROVED** [review]
Looks good

**Review by nlslatt — APPROVED** [review]

File: src/checkpoint/container/view_serialize.h [hunk 1]
```diff
@@ -313,9 +313,17 @@ inline void serialize_impl(SerializerT& s, Kokkos::DynRankView<T,Args...>& view)
...
   }
 
+  // Serialize the total number of elements in the Kokkos::View
+  size_t num_elms = view.size();
+  s | num_elms;
+
   // Construct a view with the layout and use operator= to propagate out
   if (s.isUnpacking()) {
-    if (dims == 1) {
+    if (dims == 0 and num_elms == 0) {
```
Comment (PhilMiller) [inline src/checkpoint/container/view_serialize.h]:
```suggestion
    if (is_uninitialized) {
```

Comment (PhilMiller) [reply src/checkpoint/container/view_serialize.h]: Actually, let's do this higher up

File: src/checkpoint/container/view_serialize.h [hunk 2]
```diff
@@ -313,9 +313,17 @@ inline void serialize_impl(SerializerT& s, Kokkos::DynRankView<T,Args...>& view)
     serializeLayout<SerializerT>(s, 7, layout_cur);
   }
 
+  // Serialize the total number of elements in the Kokkos::View
+  size_t num_elms = view.size();
+  s | num_elms;
+
```
Comment (PhilMiller) [inline src/checkpoint/container/view_serialize.h]:
```suggestion
  bool is_uninitialized = dims == 0 and num_elms == 0;
```

File: src/checkpoint/container/view_serialize.h [hunk 3]
```diff
@@ -337,9 +345,9 @@ inline void serialize_impl(SerializerT& s, Kokkos::DynRankView<T,Args...>& view)
     }
   }
 
-  // Serialize the total number of elements in the Kokkos::View
-  size_t num_elms = view.size();
-  s | num_elms;
+  if (dims == 0 and num_elms == 0) {
```
Comment (PhilMiller) [inline src/checkpoint/container/view_serialize.h]:
```suggestion
  if (is_uninitialized) {
```

File: tests/unit/test_kokkos_serialize_dynrankview.cc [hunk 4]
```diff
@@ -59,10 +66,40 @@ struct KokkosDynRankViewTest2D : KokkosViewTest<ParamT> { };
...
 
+TYPED_TEST_P(KokkosDynRankViewTestEmpty, test_empty_any) {
+  using namespace checkpoint;
+
+  using DataType = TypeParam;
+  using ViewType = Kokkos::DynRankView<DataType>;
+
+  ViewType in_view{};
+  auto out_view = serializeAny<ViewType>(in_view);
+  EXPECT_EQ(out_view->rank(), unsigned(0));
```
Comment (PhilMiller) [inline tests/unit/test_kokkos_serialize_dynrankview.cc:83]: Shouldn't this also check `size() == 0` - i.e. that it didn't end up looking initialized?

Comment (PhilMiller) [reply tests/unit/test_kokkos_serialize_dynrankview.cc:83]:
```suggestion
  EXPECT_EQ(out_view->rank(), unsigned(0));
  EXPECT_EQ(out_view->size(), unsigned(0));
```

**Review by PhilMiller — APPROVED** [review]

File: src/checkpoint/container/view_serialize.h [hunk 5]
```diff
@@ -313,9 +313,17 @@ inline void serialize_impl(SerializerT& s, Kokkos::DynRankView<T,Args...>& view)
...
+  s | num_elms;
+  bool is_uninitialized = dims == 0 and num_elms == 0;
   // Construct a view with the layout and use operator= to propagate out
   if (s.isUnpacking()) {
-    if (dims == 1) {
+    if (is_uninitialized) {
+      view = ViewType{};
+    } else if (dims == 0) {
+      view = constructRankedView<ViewType,0>(label, std::make_tuple(layout));
+    } else if (dims == 1) {
```
Comment (PhilMiller) [inline src/checkpoint/container/view_serialize.h:326]: We may be able to simplify a bunch of the view reconstruction logic once Kokkos 3.7 ships, since it now properly round-trips the layout associated with a View(https://github.com/kokkos/kokkos/pull/5188), and DRV will do the same https://github.com/kokkos/kokkos/pull/5026

Comment (PhilMiller) [reply src/checkpoint/container/view_serialize.h:326]: https://github.com/DARMA-tasking/magistrate/issues/254 to track  this
