### PR TITLE
113 Fix virtual derived de-serialization bug

### LINKED ISSUE #113: Virtual de-serialize from derived type fails in object registry lookup

### PR DESCRIPTION
**Pull request by lifflander**
Fixed #113

### CODE REVIEW

File: tests/unit/test_virtual_serialize.cc [hunk 1]
```diff
@@ -365,10 +377,15 @@ struct TestWrapper {
         vec.emplace_back(std::make_shared<TestDerived3>(TEST_CONSTRUCT{}));
       }
     }
+
+    for (std::size_t i = 0; i < vec_num_elms; i++) {
+      vec_derived.emplace_back(std::make_shared<TestDerived1>(TEST_CONSTRUCT{}));
```
Comment (PhilMiller) [inline tests/unit/test_virtual_serialize.cc]: It would perhaps be good to use `TestDerived2` and `TestDerived3` in exercising the case we're concerned about, since 2 is actually intermediate between `TestBase` and 3

**Comment by PhilMiller** [comment]
I agree that the test code as written does probe the failure as actually observed, though

File: tests/unit/test_virtual_serialize.cc (hunk 1 above)
Comment (lifflander) [reply tests/unit/test_virtual_serialize.cc]: Done

**Comment by lifflander** [comment]
> I agree that the test code as written does probe the failure as actually observed, though

Ok, I switched it. I concur that using the middle class is a better test.

**Review by PhilMiller — APPROVED** [review]
