### PR TITLE
130 Expand extent-only up to 4-D; make compile-time fail if not implemented

### LINKED ISSUE #130: Missing extent-only serializers > 2 dimensions
We are missing extent-only serializers for more than 2 dimensions. Also, checkpoint silently fails when the number of dimensions are > 2 due to how the templates are matched (`T = T*`).

### PR DESCRIPTION
**Pull request by lifflander**
Fixes #130

### CODE REVIEW

File: src/checkpoint/container/view_serialize.h [hunk 1]
```diff
@@ -522,25 +522,109 @@ inline void serialize(SerializerT& s, Kokkos::DynRankView<T,Args...>& view) {
...
+};
+
+template <typename SerializerT, typename ViewType, typename = void>
+struct SerializeExtentOnlyImpl;
+
+template <typename SerializerT, typename ViewType>
+struct SerializeExtentOnlyImpl<
+  SerializerT,
+  ViewType,
+  typename std::enable_if_t<CountStaticDims<ViewType>::ndims == 1>
```
Comment (PhilMiller) [inline src/checkpoint/container/view_serialize.h]: Rather than the `enable_if` that will make for lots of expansions etc, why not just specialize on `int N_DIMS`?

File: src/checkpoint/container/view_serialize.h [hunk 2]
```diff
@@ -522,25 +522,109 @@ inline void serialize(SerializerT& s, Kokkos::DynRankView<T,Args...>& view) {
...
+      v = ViewType(
+        label, view_extent_0, view_extent_1, view_extent_2, view_extent_3
+      );
+    }
+  }
+};
+
+template <typename SerializerT, typename ViewType>
+void serializeExtentOnly(SerializerT& s, ViewType& v, std::string label) {
+  SerializeExtentOnlyImpl<SerializerT, ViewType>::apply(s, v, label);
```
Comment (PhilMiller) [inline src/checkpoint/container/view_serialize.h]: Per the above comment, the `CountStaticDims<ViewType>::ndims` would then get passed as a template argument here.

Comment (PhilMiller) [reply src/checkpoint/container/view_serialize.h]: If done this way, I think the compiler errors on the case of a missing specialization would probably be somewhat better, too.

**Comment by PhilMiller** [comment]
I'm happy with this now, but having modified it, I don't think I should be the one to provide the sole approval.

**Comment by lifflander** [comment]
> I'm happy with this now, but having modified it, I don't think I should be the one to provide the sole approval.

The changes look good to me

**Review by PhilMiller — APPROVED** [review]

**Comment by PhilMiller** [comment]
If we were feeling especially ambitious, we'd find a way to make it work for arbitrary dimensions, with some sort of wild pack expansion and use of `std::iota` or something.

**Comment by PhilMiller** [comment]
Or, we'd request (propose a PR for?) Kokkos to add array-based API for getting extents and initializing new instances
